# .travis.yml files can have comments
# The language specific base vm to use for this repository
language: node_js

# The node.js version to install
node_js: "0.10.35"

# All installation prerequisites before running your build / tests go here. 
install:
  # Install deps
  - "npm install"

# All build / test commands / scripts go here.
script:
  - "npm test" # run tests